name: build_release

on:
  create:
    tags:
      - 'v*' # 触发条件为以 'v' 开头的 tag

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-os: [windows, linux, darwin]  # 可以根据需要添加或修改
        go-arch: [amd64]         # 可以根据需要添加或修改
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Build
      run: |
        sudo apt-get install libdlib-dev libblas-dev libatlas-base-dev liblapack-dev libjpeg-turbo8-dev gfortran
        ./scripts/build_archive.sh ${{matrix.go-os}} ${{matrix.go-arch}} ${{secrets.DOCKER_IMAGE_NAME}}

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.REPO_TOKEN }}
        file: ./*.tar.gz
        tag: ${{ github.ref }}
        file_glob: true
